{
 "title": "Egressd",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Egress per pods",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate({forwarder=\"vector\", dst_pod!=\"\"} | json | unwrap tx_bytes [1m])) by (src_pod, dst_pod)",
     "legendFormat": "{{src_pod}} -> {{dst_pod}}"
    }
   ]
  },
  {
   "title": "Egress per namespace",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate({forwarder=\"vector\", dst_pod!=\"\"} | json | unwrap tx_bytes [1m])) by (src_namespace, dst_namespace)",
     "legendFormat": "{{src_namespace}} -> {{dst_namespace}}"
    }
   ]
  },
  {
   "title": "Egress  per zones",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate({forwarder=\"vector\", dst_pod!=\"\"} | json | unwrap tx_bytes [1m])) by (src_zone, dst_zone)",
     "legendFormat": "{{src_zone}} -> {{dst_zone}}"
    }
   ]
  },
  {
   "title": "Egress  per IP",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate({forwarder=\"vector\"} | json | unwrap tx_bytes [1m])) by (dst_ip)",
     "legendFormat": "{{dst_ip}}"
    }
   ]
  }
 ]
}