{
 "title": "Egressd",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Egress by namespces",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(egressd_transmit_bytes_total{dst_namespace!=\"\"}[1m])) by (src_namespace, dst_namespace)",
     "legendFormat": "{{src_namespace}} to {{dst_namespace}}"
    }
   ]
  },
  {
   "title": "Egress by zones",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(egressd_transmit_bytes_total{dst_namespace!=\"\"}[1m])) by (src_namespace, dst_namespace)",
     "legendFormat": "{{src_namespace}} to {{dst_namespace}}"
    }
   ]
  },
  {
   "title": "Egress by pods (top 20)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(20, sum(rate(egressd_transmit_bytes_total{dst_pod!=\"\"}[5m])) by (src_pod, dst_pod))",
     "legendFormat": "{{src_pod}} to {{dst_pod}}"
    }
   ]
  },
  {
   "title": "Egress by pods (top 20)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(20, sum(rate(egressd_transmit_bytes_total{dst_pod!=\"\"}[5m])) by (src_pod, dst_pod))",
     "legendFormat": "{{src_pod}} to {{dst_pod}}"
    }
   ]
  },
  {
   "title": "Egress by pods to internet (top 20)",
   "type": "timeseries",
   "description": "Traffic sent to public ips",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(20, sum(rate(egressd_transmit_bytes_total{dst_ip_type=\"public\"}[5m])) by (src_pod))",
     "legendFormat": "{{src_pod}}"
    }
   ]
  },
  {
   "title": "Egress by protocol",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(egressd_transmit_bytes_total{}[5m])) by (proto)",
     "legendFormat": "{{src_pod}}"
    }
   ]
  }
 ]
}