apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "egressd.exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "egressd.exporter.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- tpl (mergeOverwrite (tpl .Values.exporter.config . | fromYaml) .Values.exporter.structuredConfig | toYaml) . | nindent 4 }}
