apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "egressd.exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "egressd.exporter.labels" . | nindent 4 }}
    app.kubernetes.io/component: aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "egressd.exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/exporter-configmap.yaml") . | sha256sum }}
      {{- if .Values.exporter.prometheusScrape.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{.Values.exporter.httpListenPort}}"
      {{- end }}
      {{- with .Values.collector.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "egressd.exporter.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "egressd.exporter.serviceAccountName" . }}
      dnsPolicy: {{.Values.collector.dnsPolicy}}
      securityContext:
        {{- toYaml .Values.collector.podSecurityContext | nindent 8 }}
      containers:
        - name: exporter
          image: "{{ .Values.exporter.image.repository }}:{{ .Values.exporter.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          securityContext:
            {{- toYaml .Values.exporter.containerSecurityContext | nindent 12 }}
          args:
            - "-http-listen-port={{.Values.exporter.httpListenPort}}"
        {{- range $key, $value := .Values.exporter.extraArgs }}
        {{- if $value }}
            - "-{{ $key }}={{ $value }}"
        {{- else }}
            - "-{{ $key }}"
        {{- end }}
        {{- end }}
          env:
            {{- if.Values.castai.apiKey }}
            - name: CASTAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{- include "egressd.fullname" . }}"
                  key: API_KEY
            {{- end }}
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: http-server
              containerPort: {{ .Values.exporter.httpListenPort }}
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/egressd/config
          livenessProbe:
            httpGet:
              port: http-server
              path: /healthz
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: http-server
              path: /healthz
            initialDelaySeconds: 5
            periodSeconds: 5
      terminationGracePeriodSeconds: 10
      volumes:
        - name: config
          {{- if .Values.exporter.existingSecretForConfig }}
          secret:
            secretName: {{ .Values.exporter.existingSecretForConfig }}
          {{- else }}
          configMap:
            name: {{ include "egressd.exporter.fullname" . }}
          {{- end }}
---
{{- if .Values.exporter.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "egressd.exporter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "egressd.labels" . | nindent 4 }}
  {{- with .Values.exporter.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "egressd.exporter.fullname" . }}
  labels:
    {{- include "egressd.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "egressd.exporter.fullname" . }}
  labels:
    {{- include "egressd.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "egressd.exporter.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "egressd.exporter.serviceAccountName" . }}
    namespace: {{.Release.Namespace}}
{{- end }}
