{{- if .Values.collector.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "egressd.collector.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "egressd.labels" . | nindent 4 }}
  {{- with .Values.collector.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "egressd.fullname" . }}
  labels:
    {{- include "egressd.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  #- nodes
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "egressd.fullname" . }}
  labels:
    {{- include "egressd.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "egressd.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "egressd.collector.serviceAccountName" . }}
  namespace: {{.Release.Namespace}}
{{- end }}
